import OrderFilter from '@/Components/OrderFilter';
import { Header } from '@/styles/header';
import Head from 'next/head';
import { Main } from './styles';
import Propertie from '@/Components/Propertie';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Header>
        <h1>Venda de imóveis</h1>
      </Header>
      <Main>
        <OrderFilter />

        <Propertie />
        <Propertie />
      </Main>
    </>
  );
}
